# Generated by Django 2.2.16 on 2020-11-09 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201110_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 11, 10, 1, 39, 36, 306564), verbose_name='Опубликована'),
        ),
    ]
